# Generated by Django 2.2.11 on 2020-03-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200326_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='saed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_saed', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='test',
            name='sdsd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sdsd', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='test',
            name='testhg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_testhg', to='home.CustomText'),
        ),
    ]
